server:
#  port: 8081
  port: 8761
spring:
  #  profiles:
  #    active: web, prod
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_seminar3
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
  application:
    name: Pegas
#  config:
#    import: configserver:http://localhost:8888
#    profiles:
#      active: default
  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
        defaultZone: http://127.0.0.1:8761/eureka